### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/evaluacion-intermedia-modulo-2-sandrusmb#6]
Really cool job @sandrusmb  !!!

Here you have some tips to improve the exercise:

### JavaScript: basic

- [ ] On page load, execute 'getRandomNumber' function and store the returned value on a constant to work with it later.
- [ ] If you call 'getRandomNumer' function inside the event callback, you will be creating a new random number each time the user clicks the button. That makes the game really complex and the hints will not have sense. Let's generate the random number when the page loads instead.
- [ ] Define the logic to make the counter work.
- [ ] Fix the if's structure: check for one option, then the other and then for the rest is enough with an `else` statement.
- [ ] Remember that every time we use `.innerHTML` or `.value` to get DOM content we receive a string. Sometimes we will need to use something like `parseInt()` to convert it to a number.
- [ ] If we repeat several times `parseInt(value)` within a function it is better set it in a constant.

### JavaScript: advanced

- [ ] Move you counter logic into a function and execute it on each click.
- [ ] You are writing many times "trackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'trackEl'?
- [ ] Put `ev.preventDefault()` to first line of the function.

### Structure

- [ ] In the statement of the exercise, it was not necessary to use the Starter Kit

### HTML

- [ ] Add form
- [ ] Add HTML elements for the game: title, label, input, button, space for feedback (`div`, `p`) and number of trials.
- [ ] Use a `label` to define the content of the input.
- [ ] Connect the label to the input using the `for` attribute of the label and the `id` of the input.
- [ ] Move all input inside form.
- [ ] Use placeholder.

### Steps to finish the game (for those far from the solution)

You are close to the exercise solution, but here you have a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables.
2. Generate the random number and save it to a variable.
3. Init counter of trials to 0.
4. Define a function that executes when the user clicks on the button, that
  - increments the counter and paints its value in the HTML.
  - collect the value of the HTML input and compare it with the random number.
    - if they are equal, draw a 'You Win' message.
    - if it's lower, draw a 'Too short' message.
    - if it's higher, draw a 'Too long' message.
5. Assign a listener to the button click to execute the previous function.

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

**Comment by sandrusmb** [comment]
Hola @migueldelmazo, 

Hice algunas mejoras en el código de la evaluación intermedia por si quieres echarle un ojo. 

Muchas gracias, 

Sandra

**Comment by migueldelmazo** [comment]
Hola @sandrusmb,

la parte de JS está perfecto. La parte de HTML le faltaría un form para tener más semántica y al añadir a lo mejor te toca cambiar alguna cosilla en el JS.

Además, marca las mejoras que has hecho en la descripción de esta issue please.

Muy buen trabajo señora, puedes estar contenta.
